server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = /docs {
        return 301 /docs/;
    }

    location /docs/ {
        rewrite ^/docs/(.*)$ /$1 break;
        try_files $uri $uri/ /index.html;
    }

    location /specs/ {
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
