apiVersion: v1
kind: Secret
metadata:
  name: asset-monitoring-system-secrets
type: Opaque
stringData:
  db-username: asset_monitoring_system
  db-password: asset_monitoring_system
  rabbitmq-user: asset_monitoring_system
  rabbitmq-password: asset_monitoring_system
  rabbitmq-vhost: /
  rabbitmq-exchange: asset_monitoring_system.events
  mail-from-address: no-reply@assetmonitoringsystem.local
  slack-webhook-url: ""
